### ISSUE TITLE
[CTS 32] Unnecessary depth and duplication in directory structure

### ISSUE THREAD

**Issue by carygravel** [PhilterPaper/Perl-PDF-Builder#126]
`lib/PDF/Builder/Basic/PDF` duplicates `PDF`, which is anyway the only thing in the `Basic` directory.

I suggest that the second `PDF`directory be eliminated.

**Comment by PhilterPaper** [comment]
What do you mean by "duplicates PDF"? The files under Basic/PDF/ are completely different from the files under lib/PDF/. What do you see it duplicating? Or are you saying that it should just be Basic/ (eliminate the unnecessary "PDF" under it)? This is the original structure inherited from PDF::API2, which in turn inherited it from an earlier predecessor.  I suppose the extraneous "PDF" subdirectory level _could_ be removed, but I'm not sure it's worth the effort (lots of code needs to be changed). I agree that it appears to be unnecessary, but at this late date, I'm more concerned that I might break something in some application's code (not that they _should_ be calling low-level routines directly, but sometimes they do that).

**Comment by carygravel** [comment]
I would say that deprecating the structure is only necessary when it is part of the published API, and that anything "under the hood" is fair game.

**Comment by PhilterPaper** [comment]
Unfortunately, even though the use of internal ("under the hood") interfaces is discouraged, they _are_ somewhat documented in the POD. Someone _could_ be using some of them as utilities. Therefore, giving plenty of advance warning (via deprecation) would be required.

I suspect that way back when, someone grabbed a bunch of PDF-oriented routines from some "Basic" Perl library. The library directory structure was Basic/PDF, and they didn't bother to clean it up to just Basic. Thus we still have Basic/PDF. I've always been a bit annoyed by that superfluous "PDF", but I'll have to mull over whether it's worth the bother to change it.

**Comment by PhilterPaper** [comment]
I discussed this with Steve Simms (PDF::API2 owner), and he had thought about doing this earlier (replacing `Basic/PDF/` with `Core/`). What stopped him was not wanting to unnecessarily break the code of any application that _was_ using these routines directly. Since he's not interested in changing PDF::API2, my changing PDF::Builder alone would break compatibility with PDF::API2. Therefore, I think I'll just leave well enough alone and keep the `Basic/PDF/` path as it is. It's not a tremendous impact on typing, space, or execution time; certainly not enough to warrant the disruption of changing it.
