### ISSUE TITLE
test failures with ghostscript > 9.55.0

### ISSUE THREAD

**Issue by carygravel** [PhilterPaper/Perl-PDF-Builder#184]
Tests t/tiff.t 13 and 16 fail with 9.56.0 and 9.56.1:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1009448

I assume this is the same problem that made you disable the tests for windows.

**Comment by PhilterPaper** [comment]
Somewhere in there, someone says they think it is (may be?) the same problem seen with lcms2 2.13, which was fixed in 2.13.1. It's not clear to me whether the newly reported failure was in 2.13 or 2.13.1. Can you tell? And is it the same failure as reported earlier in #177? There seems to be a difference in test numbering.

Most importantly, is this something that needs to be fixed in PDF::Builder code, or is the problem in building libtiff or even one of the test utilities? I haven't looked yet to see if this is the same failure as with the CI tests on Windows.

**Comment by PhilterPaper** [comment]
Since GS is used in more than just those two tests (13 and 16), I'm not sure we want to kill _all_ the GS-using tests if it's version 9.56.0 or 9.56.1 (and maybe more to come). Maybe a test to get the version number and compare it against an exclusion list array could be added to those two tests? That shouldn't be too hard to do. This could be used on other tests and for ImageMagick should the need arise to exclude certain versions.

Are the failing test numbers (13 and 16) correct for the current tiff.t in GitHub, or have they changed (from an older version)? It would be good to know the test names, just to confirm.

**Comment by carygravel** [comment]
Debian has the latest version of PB. If you follow the link to the bug report, you will see the tests are:

13 - lzw+horizontal predictor (not converted to flate) with GT

16 - lzw+horizontal predictor (not converted to flate) without GT

**Comment by carygravel** [comment]
It looks to me like a bug in GS. Alternatively, GS could be falling over in a really ungraceful manner because of something it doesn't like in the PDF. Either way, that version of GS isn't going to hit the GitHub Linux runners for some time. I'll forward the problem to the GS maintainers and see what they say. I suggest we leave this open until we have a fix. Maybe that will allow us to enable the Windows tests again.

**Comment by PhilterPaper** [comment]
OK, thanks for chasing this down. If it will be a while before GS gets fixed, I was thinking of modifying t/tiff.t to take `$gs` and run it through a new function to get `$gsX`, where we get the version and see if it's in an exclusion list. Use `$gsX` instead of `$gs` for those two tests. I could release an update with this if it will bring PDF::Builder back on line for these distributions. Then I could see if this permits enabling one or more Windows tests in test.yml. Do you think this would be useful?

**Comment by carygravel** [comment]
I would hold off doing anything before we have confirmation from the GS maintainer on the cause. Maybe there is something in the PDF that is non-standard, but that the other viewers have been accepting.

Assuming it turns out to be a bug in GS that is fixed in, say 9.56.2, then your solution sounds fine to me.

**Comment by PhilterPaper** [comment]
OK, sounds good. I'll wait.

**Comment by PhilterPaper** [comment]
> Maybe that will allow us to enable the Windows tests again.

Two months ago I had to disable Basic Windows because GD wouldn't build (see RT 141125 under GD). The owner said he was working on it. Once that CI test can be re-enabled, we can look at the problems with Full Windows (including TIFF).

**Comment by ppisar** [comment]
The two t/tiff.t failures are bugs a new PDF interpreter of the new ghostscript. <https://bugs.ghostscript.com/show_bug.cgi?id=705849>. Ghostscript has already committed a fix.

**Comment by PhilterPaper** [comment]
I released a new version last night that skips the two tiff.t tests if Ghostscript 9.56.0 or 9.56.1. CPANTS doesn't seem to be working, so I can't yet see whether this was successful for the testers. Have you seen evidence of problems with this?

I see that you opened a PR; I will look at it today.

**Comment by ppisar** [comment]
I saw your new release. That's how I got to this issue. (Fedora already patched broken ghostscript.) I confirm that the new release correctly skips the affected tests. (And I also confirm that the tests pass with the patched ghostscript when I edit them no to skip because of ghostscript.)

**Comment by PhilterPaper** [comment]
Since I've dealt with the immediate problem (GS 9.56.* is now bypassed), I'll go ahead and close this. Thanks for the testing!

**Comment by jonassmedegaard** [comment]
Ghostscript package maintainer for Debian here.

For the record, I just now tested against Ghostscript 10.0.0 where this issue seems fixed.

**Comment by PhilterPaper** [comment]
Thanks. For the recent PDF::Builder 3.024 release, I skip some tests if using Ghostscript 9.56.0 and 9.56.1 -- I'll probably have to leave that skip in (t/tiff.t). Good to hear that GS 10 works OK -- all 19 t tests should be run with that version.
