### ISSUE TITLE
Options for text formatting

### ISSUE THREAD

**Issue by abeverley** [PhilterPaper/Perl-PDF-Builder#185]
This is an issue for discussing the implementation of text formatting options in PDF::Builder.

References: Section II [para D](https://metacpan.org/release/PMPERRY/PDF-Builder-3.023/source/INFO/RoadMap#L280) and [para E](https://metacpan.org/release/PMPERRY/PDF-Builder-3.023/source/INFO/RoadMap#L293) of the roadmap. [Issue #74 from PDF::Table](https://github.com/PhilterPaper/PDF-Table/issues/74).

I have 2 reasons for requesting this (both completely separate):

1. I have a need to use different fonts and text colors in a cell in PDF::Table. My use-case is a list of "tick" and "cross" bullet points. The ticks need to be green and use a font that contains a tick character (e.g. ✔). The crosses need to be red and use a font that contains a cross character (e.g. ✘). All need to be in the same cell.
2. I have a WYSIWYG editor that users enter formatted text content. This is saved as markdown. I would like to be able to easily convert this markdown-formatted user content into a PDF.

As I mentioned previously, I am happy to sponsor this. I provisionally engaged @domm a while ago or I am happy to sponsor @PhilterPaper (or both).

What is the best way to take this forward?

Many thanks and sorry for taking so long to raise this issue!

**Comment by PhilterPaper** [comment]
OK, I have spent some time thinking about what will be needed to support your requests. It appears to be a fairly large update to PDF::Builder (and a somewhat smaller one to PDF::Table). First of all, number 1 sounds like you need some embedded control codes to change fonts, colors, and font sizes, as well as some sort of "entity" codes to specify the two special characters. I'm thinking that eventually users like you will want to do many other text controls, such as italic, bold, underline, etc., so I should be careful about hard coding in very application-specific codes that would be difficult to expand. I assume that something like an HTML markup tagged language would be desired on your end. Specifics listed below, but does that sound like where you want to go?

For number 2, how full a markdown language are you looking to use for text? Markdown is not as standardized as HTML or other markup languages, so I would need a list, or a reference URL. We might need to support several flavors of Markdown, but can start with the one you need. I assume that this is for a full page, rather than for within a table cell -- is this correct?

### Plan of attack:
**I.** We need to support a number of fonts at one time (e.g., flavors of Times, plus Zapf Dingbats), that associate a font face (e.g., Times) with normal, italic, and bold; with the appropriate font file or other designation. The system could come preloaded with the core fonts, and have an API to allow other fonts to be defined in a similar way. A font would not actually be loaded until its use is requested, and one font would be designated as the default or initial font to use, should it not be given explicitly. Each entry in the global table for this would include information such as the font face (e.g., Times), type (core, TTF, PS, etc.), flags for italic and bold, the filename(s) to use (or for corefonts, the name), and perhaps information on how to synthesize bold, oblique, small/petite caps, etc. There would also be a used flag, initially -1 (unused), and after that a unique index 0,1,2,... when the font has been opened/loaded; and the index is used to refer to it elsewhere.

When a given font entry is requested, and is found, open or load the font if it isn't already, and return the font object for use, such as `$text->font($fontObj, $size)`. One thing which I plan to eventually implement, is to allow UTF-8 encoding for what are currently single-byte fonts (core, PS, etc.) by defining on a page-by-page basis subfonts which build up the needed glyph library (128 assorted characters plus ASCII). This would necessitate translating the text on-the-fly to use the entry number in the currently active subfont. Anyway, that's future work, but I want to make sure I have a framework that allows it in the future.

**II.** The user-provided text will have some sort of markup within it. Candidates include HTML, Pango (slightly different from HTML), Markdown (several flavors), *roff, and perhaps others eventually. I don't see any reason to handle TeX or LaTeX, as they already have nice PDF output. The basic ones which result in font selection or sizing will be built in, while others might have callbacks to handle more complicated operations. These could include underline/strike/overline, switch between LTR and RTL, suppress (or use) a specific ligature, the human language (for hyphenation), etc. Custom tags with callbacks could be done. When processing this marked-up text, something like HTML entities (named, decimal, hex Unicode values) should be supported, where individual characters replace the entities.

I looked at Text::Layout to handle this part of it, but it's very frustrating. It seems to work well only on Linux systems, and counts on having a built-in font configuration system (that Windows lacks). The samples don't work without massive changes, and even then I can't get most of them to work. According to the author, I _should_ be able to look at the internal state, where the Pango markup has been processed, and avoid putting any ink on paper, but it appears that will require extending the API of Text::Layout, and there's no sign of such things happening. So, at this point, I think I'm going to have to write a number of translators for various markup languages, rather than just being able to use Text::Layout. It's Pango only, so other translators will have to be written anyway and it's not a tremendous loss.

Anyway, once the marked-up text has been parsed, the original single string (usually a paragraph's worth of text) will be broken up into an array of hashes. Each element would contain a segment of the text with the same properties (font and style, color, size, etc.) and other information as needed, such as the font index number, size, color, etc. These elements might be broken up to fit a line, and so starting x,y, minimum leading, and maybe word-splitting information (hyphenation) might be included. The idea is to provide enough information to properly render this text, and make it easy to glue together a series of elements onto one line.

**III.** Hopefully, existing PDF::Builder text routines can be enhanced to accept either a single string, or an array of hashes as described above. The alternative would be to write entire new ones. We might have a column-fitting routine that breaks up array elements or glues them together to fill a line, but doesn't itself put ink to paper. In the future, this might call HarfBuzz::Shaper and Text::KnuthPlass to do text shaping and paragraph shaping. PDF::Builder will be enhanced to support proper hyphenation via Text::Hyphen or similar, although for the time being it will still be a _greedy_ algorithm for line breaking. There will be some sort of global setting to tell PDF::Builder what markup is being used, as well as whether to use HarfBuzz::Shaper and Text::KnuthPlass.

Of special concern is compatibility with PDF::Table, so that if you're using it with PDF::Builder, you can do all this text markup, but can still be used in the old manner with PDF::API2. The `advancewidth()` routine in PDF::Builder will be able to measure the width of words and text chunks, and proper hyphenation calls should replace the primitive forced splitting currently used in PDF::Table (that ought to work with PDF::API2, too). A table cell is just a column with a narrow width, so new PDF::Builder facilities should be usable to figure out how to lay out a cell's text.

Well, those are my thoughts at the moment. As I said, to do this properly and allow future expansion of capabilities, I've tried to architect it to be clean and flexible, although a lot of stuff at this point is still mostly hand-waving. I've got plenty of other stuff on my plate for PDF::Builder, PDF::Table, Text::KnuthPlass, and possibly a new Text::KnuthLiang hyphenator, so help from others with feedback on design and testing, and maybe even some coding, would be appreciated, as would $$ through sponsorship. My biggest concern with accepting money right now is that would create pressure to get it done quickly, for which I just don't have the time in my life (if I do all the work), and I don't want to cut corners. Users out there _do_ have a need for new features, but I'm reluctant to try to estimate a time frame for work of this significant scale.

**Comment by PhilterPaper** [comment]
I have found packages for parsing both Markdown and HTML (part of section II), but I still need to process them fully after parsing, before handing over the information to the Builder routines (section III). So, some progress. Unfortunately, I still have a lot of stuff queued up before I can get to this request (late summer, at best, I think).

**Comment by abeverley** [comment]
Thanks for all this @PhilterPaper - looks great and well thought-out. I'm not sure that I personally have much need for entities in their own right, as long as there is some way of inserting unicode characters, maybe using fallback characters as you suggest, or certainly being able to change the font manually to one that supports the required glyph.

In terms of what Markdown version to support, my general assumption is that only the basic syntax can be relied upon, so as long as simple things such as bold, italics, headings and links are available then that should be fine.

I can certainly arrange some sponsorship, although I note your points about time constraints. I may also be able to sponsor other developers if that helps (I mentioned @domm before). Maybe we can take this discussion offline - I'll drop you a line separately now.

**Comment by abeverley** [comment]
> In terms of what Markdown version to support, my general assumption is that only the basic syntax can be relied upon, so as long as simple things such as bold, italics, headings and links are available then that should be fine.

Just to note that lists/bullets will be required as well.

**Comment by sciurius** [comment]
> It seems to work well only on Linux systems, and counts on having a built-in font configuration system (that Windows lacks).

Given the number of people that are happily using it on Windows, indirectly via ChordPro, this is a suprising remark.

I admit that the tests/examples are developed and used on linux, but to have them run on Windows is fairly trivial. For your convenience I've updated a couple of tests (`tl_c_01.pl` and `tl_c_02.pl`) to run on Windows. Check out version 0.030_001 from git.

**Comment by PhilterPaper** [comment]
I was able to upgrade to 0.030_001 from 0.029, but I had to modify 3 or 4 .pm files to hard-code the version number. CPAN on Windows/Strawberry Perl doesn't seem to like `our $VERSION = $Text::Layout::Version::VERSION;`. I haven't yet had time to play with anything, but at least it's now installed and the t-tests presumably ran OK.

**Comment by PhilterPaper** [comment]
This facility is now in release 3.025, so I'm closing it.
